const fs = require("fs");

/**
 * Reads themes from a markdown file generated by Phase 1.
 * @param {string} filePath - Path to the markdown file
 * @returns {Promise<string[]>} Array of theme lines
 */
async function readThemesFromMarkdown(filePath) {
  return new Promise((resolve, reject) => {
    fs.readFile(filePath, "utf8", (err, data) => {
      if (err) {
        reject(err);
        return;
      }

      try {
        const lines = data.split(/\r?\n/);
        const themes = [];

        for (const line of lines) {
          const trimmedLine = line.trim();

          // Look for lines that start with "- " (bullet points)
          if (trimmedLine.startsWith("- ") && !trimmedLine.startsWith("- **")) {
            const theme = trimmedLine.substring(2).trim(); // Remove "- " prefix
            if (theme.length > 0) {
              themes.push(theme);
            }
          }
        }

        resolve(themes);
      } catch (error) {
        reject(error);
      }
    });
  });
}

module.exports = { readThemesFromMarkdown };
